export const dummyInfo = [
  {
    imageSrc:
      "https://rukminim2.flixcart.com/image/312/312/kzogn0w0/mobile/m/p/2/-original-imagbmf4qsurna5j.jpeg?q=70",
    title: "Realme 9 Pro+ 5G (Sunrise Blue, 256 GB)",
    rating: "2,280 Ratings",
    specifications: [
      "8 GB RAM | 256 GB ROM",
      "16.26 cm (6.4 inch) Full HD+ AMOLED Display",
      "50MP + 8MP + 2MP | 16MP Front Camera",
      "4500 mAh Li-ion Battery",
      "Mediatek Dimensity 920 Processor",
      "1 Year Warranty for Phone and 6 Months Warranty for In-Box Accessories",
    ],
    price: "₹28,999",
    discount: "31,999",
    deliveryDate: "25th Apr",
    offer: "₹13,000",
    bankOffer: "Bank Offer",
    star: "4.3",
  },
  {
    imageSrc:
      "https://rukminim2.flixcart.com/image/312/312/kzogn0w0/mobile/m/p/2/-original-imagbmf4qsurna5j.jpeg?q=70",
    title: "Realme 9+ Pro+ 5G (Sunrise Blue, 256 GB)",
    rating: "2,280 Ratings",
    specifications: [
      "8 GB RAM | 256 GB ROM",
      "16.26 cm (6.4 inch) Full HD+ AMOLED Display",
      "50MP + 8MP + 2MP | 16MP Front Camera",
      "4500 mAh Li-ion Battery",
      "Mediatek Dimensity 920 Processor",
      "1 Year Warranty for Phone and 6 Months Warranty for In-Box Accessories",
    ],
    price: "₹28,999",
    discount: "31,999",
    deliveryDate: "25th Apr",
    offer: "₹13,000",
    bankOffer: "Bank Offer",
    star: "4.3",
  },
  {
    imageSrc:
      "https://rukminim2.flixcart.com/image/312/312/kzogn0w0/mobile/m/p/2/-original-imagbmf4qsurna5j.jpeg?q=70",
    title: "realme 9+ Pro+ 5G (Sunrise Blue, 256 GB)",
    rating: "2,280 Ratings",
    specifications: [
      "8 GB RAM | 256 GB ROM",
      "16.26 cm (6.4 inch) Full HD+ AMOLED Display",
      "50MP + 8MP + 2MP | 16MP Front Camera",
      "4500 mAh Li-ion Battery",
      "Mediatek Dimensity 920 Processor",
      "1 Year Warranty for Phone and 6 Months Warranty for In-Box Accessories",
    ],
    price: "₹28,999",
    discount: "31,999",
    deliveryDate: "25th Apr",
    offer: "₹13,000",
    bankOffer: "Bank Offer",
    star: "4.3",
  },
];
